### ISSUE TITLE
Cannot install sippy_cup on CentOS 8 (minimal install)

### ISSUE THREAD

**Issue by Palezvar** [mojolingo/sippy_cup#111]
I tried to compile sippy_cup from source code but getting the following error when I try to start a test scenario that I copied from the github web site:
```
[root@sip-centos1 ~]# /root/sippy_cup/bin/sippy_cup -r test.yml
Traceback (most recent call last):
        2: from /root/sippy_cup/bin/sippy_cup:3:in `<main>'
        1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- sippy_cup (LoadError)
        21: from /root/sippy_cup/bin/sippy_cup:3:in `<main>'
        20: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:147:in `require'
        19: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
        18: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:158:in `require'
        17: from /usr/local/share/gems/gems/sippy_cup-0.7.2/lib/sippy_cup.rb:7:in `<top (required)>'
        16: from /usr/local/share/gems/gems/sippy_cup-0.7.2/lib/sippy_cup.rb:7:in `each'
        15: from /usr/local/share/gems/gems/sippy_cup-0.7.2/lib/sippy_cup.rb:7:in `block in <top (required)>'
        14: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
        13: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
        12: from /usr/local/share/gems/gems/sippy_cup-0.7.2/lib/sippy_cup/scenario.rb:4:in `<top (required)>'
        11: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
        10: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
         9: from /usr/local/share/gems/gems/activesupport-7.0.2.3/lib/active_support/core_ext/hash.rb:3:in `<top (required)>'
         8: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
         7: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
         6: from /usr/local/share/gems/gems/activesupport-7.0.2.3/lib/active_support/core_ext/hash/conversions.rb:3:in `<top (required)>'
         5: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
         4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:94:in `require'
         3: from /usr/local/share/gems/gems/activesupport-7.0.2.3/lib/active_support/xml_mini.rb:11:in `<top (required)>'
         2: from /usr/local/share/gems/gems/activesupport-7.0.2.3/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
         1: from /usr/local/share/gems/gems/activesupport-7.0.2.3/lib/active_support/xml_mini.rb:103:in `backend='
/usr/local/share/gems/gems/activesupport-7.0.2.3/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
```

Before cloning the repo and running "bundle install", I executed the following to prep the environment:
```
dnf -y install dnf-plugins-core
dnf upgrade
dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf config-manager --set-enabled powertools
dnf -y group install "Development Tools"
dnf -y install make cmake gcc-c++ ncurses-devel openssl-devel flex bison libpcap libpcap-devel lksctp-tools-devel git
dnf module install ruby:2.7
dnf install ruby-devel
```

Am I missing a dependency? I am using sipp 3.7.

Thanks

**Comment by devhossamali** [comment]
Its not compatible with activesupport-7.0.2.3 try to downgrade to activesupport- 5.0.0.1 and try again
