### ISSUE TITLE
installing on mac (m3)

### ISSUE THREAD

**Issue by davidcsi** [mojolingo/sippy_cup#115]
% gem install bundler --no-ri --no-rdoc
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-ri

**Comment by bklang** [comment]
Hi @davidcsi 

This project hasn't been maintained in quite a while, so I can't vouch whether it will work today. However, that error you got can be safely ignored. It was attempting to skip doc generation, but you can leave it out like this:

```shell
gem install bundler
```

**Comment by davidcsi** [comment]
thanks @bklang it's failing on different things now... you're right, it's not maintained.
```
make failed, exit code 2

Gem files will remain installed in /usr/local/bundle/gems/nokogiri-1.10.10 for inspection.
Results logged to /usr/local/bundle/extensions/aarch64-linux/3.3.0/nokogiri-1.10.10/gem_make.out

  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /usr/local/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:206:in `install'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.

In Gemfile:
  sippy_cup was resolved to 0.7.2, which depends on
    nokogiri
```
though i installled nokogiri
```
gem install nokogiri
```
Thanks!
